beautyproduct_project/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('beautystore_app.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# If DEBUG is True, serve static files using Django
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

beautystore_app/urls.py
from django.urls import path,include
from . import views 
from django.contrib import admin
from .views import SellerLoginView


urlpatterns=[
    path('',views.index,name='index'),
    path('customer_dashboard/',views.customer_dashboard,name='customer_dashboard'),
    path('about',views.about,name='about'),
    path('add/', views.product_add, name='product_add'),
    path('<int:pk>/update/', views.product_update, name='product_update'),
    path('<int:pk>/delete/', views.product_delete, name='product_delete'),
    path('products/', views.admin_product_page, name='admin_product_page'),
    path('admin_login/', views.admin_login, name='admin_login'),
    path('accounts/', include("django.contrib.auth.urls")),
    path('register/', views.register, name='register'),
    path('login/', views.login_view, name='login'),
    path('change_password/', views.change_password, name='change_password'),
    path('forgot_password/', views.forgot_password, name='forgot_password'),
    path('reset_password/<uidb64>/<token>/', views.reset_password, name='reset_password'),
    path('logout/', views.user_logout, name='logout'),
    path('edit_customer/', views.edit_customer, name='edit_customer'),
    path('address/', views.address_list, name='address_list'),
    path('address/add/', views.address_create, name='address_create'),
    path('address/edit/<int:pk>/', views.address_edit, name='address_edit'),
    path('address/delete/<int:pk>/', views.address_delete, name='address_delete'),
    path('search/', views.product_search, name='product_search'),
    path('product/<int:product_id>/', views.product_details, name='product_details'),
    path('wishlist/', views.wishlist, name='wishlist'),
    path('add_to_wishlist/<int:product_id>/', views.add_to_wishlist, name='add_to_wishlist'),
    path('remove_from_wishlist/<int:product_id>/', views.remove_from_wishlist, name='remove_from_wishlist'),
    path("cart/", views.cart, name="cart"),
    path('add_to_cart/', views.add_to_cart, name='add_to_cart'),
    path('cart/increase/<int:cart_item_id>/', views.increase_quantity, name='increase_quantity'),
    path('cart/decrease/<int:cart_item_id>/', views.decrease_quantity, name='decrease_quantity'),
    path('delete_item_in_cart/<int:id>/', views.delete_item_in_cart, name='delete_item_in_cart'),
    path('checkout/', views.checkout, name='checkout'),
    path('category/<int:category_id>/', views.category_products, name='category_products'),
    path('subcategory/<int:subcategory_id>/', views.subcategory_products, name='subcategory_products'),
    path('order_list/', views.order_list, name='order_list'),
    path('order_detail/<int:order_id>/', views.order_detail, name='order_detail'),
    path('seller_login/', SellerLoginView.as_view(), name='seller_login'),
    path('create_purchase_order/', views.CreatePurchaseOrderView.as_view(), name='create_purchase_order'),
    path('seller/purchase_orders/', views.seller_purchase_orders, name='seller_purchase_orders'),
    path('seller/purchase_order/<int:purchase_order_id>/', views.purchase_order_details, name='purchase_order_details'),
    path('reject_purchase_order/<int:purchase_order_id>/', views.reject_purchase_order, name='reject_purchase_order'),
]

beautystore_app/models.py
from decimal import Decimal
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
from django.core.validators import MinLengthValidator


class Seller(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, null=True)
    name = models.CharField(max_length=100)
    email = models.EmailField(unique=True)
    phone_no = models.CharField(max_length=12, unique=True, validators=[MinLengthValidator(10)])
    address = models.CharField(max_length=255)
    
    def __str__(self):
        return self.name
    
class Category(models.Model):
    category_name = models.CharField(max_length=100, unique=True)
    
    def __str__(self):
        return self.category_name

class Subcategory(models.Model):
    subcategory_name = models.CharField(max_length=100)
    parent_category = models.ForeignKey(Category, on_delete=models.CASCADE)
    
    def __str__(self):
        return self.subcategory_name


# Create your models here.
class Product(models.Model):
    name = models.CharField(max_length=255)
    price = models.FloatField()
    stock = models.IntegerField()
    image = models.ImageField(upload_to='product_images/')
    description = models.TextField()
    quantity_available = models.PositiveIntegerField(default=0)
    brand = models.CharField(max_length=255)
    expiry_date = models.DateField(null=True, blank=True)
    skin_concern = models.CharField(max_length=255, null=True, blank=True)
    skin_type = models.CharField(max_length=255, null=True, blank=True)
    ingredients = models.TextField(null=True, blank=True)
    product_type = models.CharField(max_length=255, null=True, blank=True)
    country_of_origin = models.CharField(max_length=255, null=True, blank=True)
    seller = models.ForeignKey(Seller, on_delete=models.CASCADE)
    subcategory = models.ForeignKey(Subcategory, on_delete=models.CASCADE)
    quantity_in_stock = models.PositiveIntegerField(default=0)
    reorder_level = models.PositiveIntegerField(default=0)
    cost = models.DecimalField(max_digits=10, decimal_places=2,default=100)

    def __str__(self):
        return self.name

    

    
    

    
class Offer(models.Model):
    code = models.CharField(max_length=16)
    description = models.CharField(max_length=255)
    discount = models.FloatField()


class Wishlist(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)

    def __str__(self):
        return f'{self.user.username} Wishlist'
    
    
class Address(models.Model):
    recepient_name = models.CharField(max_length=100, null=True)
    recepient_contact = models.CharField(max_length=20, null=True)
    address_line1 = models.CharField(max_length=255)
    address_line2 = models.CharField(max_length=255, blank=True, null=True)
    city = models.CharField(max_length=100)
    state = models.CharField(max_length=100)
    postal_code = models.CharField(max_length=20)
    customer = models.ForeignKey('Customer', on_delete=models.CASCADE, null=True, blank=True)

    def __str__(self):
        return f"{self.address_line1}, {self.address_line2}, {self.city}, {self.state} - {self.postal_code}"    

class Customer(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, null=True)
    customer_name = models.CharField(max_length=100)
    contact_number = models.CharField(max_length=20, blank=True, null=True)
    email = models.EmailField(unique=True)
    password = models.CharField(max_length=255)
    role = models.CharField(max_length=50, default='customer')

    def __str__(self):
        return self.customer_name
    
class Cart(models.Model):
    customer = models.ForeignKey(Customer, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    quantity = models.IntegerField(default=0)

    def sub_total(self):
        return int(self.product.price) * int(self.quantity)

    def __str__(self):
        return f"Cart - Customer: {self.customer.customer_name} - Product: {self.product.product_name} - Qty: {self.quantity}"


class Order(models.Model):
    STATUS_CHOICES = [
        ('Pending', 'Pending'),
        ('Placed', 'placed'),
        ('Shipped', 'Shipped'),
        ('Delivered', 'Delivered'),
    ]
    customer = models.ForeignKey(Customer, on_delete=models.CASCADE)
    address = models.ForeignKey(Address, on_delete=models.CASCADE)
    order_date = models.DateTimeField(default=timezone.now)
    status = models.CharField(max_length=20, choices=STATUS_CHOICES, default='Pending')

    def total_price(self):
        return sum(item.total_price() for item in self.orderitem_set.all())

    def __str__(self):
        return f"Order - Customer: {self.customer.customer_name} - Status: {self.status}"

class OrderItem(models.Model):
    order = models.ForeignKey(Order, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField()

    def total_price(self):
        return self.product.price * self.quantity

    def __str__(self):
        return f"Order Item - Order: {self.order.id} - Product: {self.product.name} - Qty: {self.quantity}"



# Define the PurchaseOrder model
class PurchaseOrder(models.Model):
    TotalAmount = models.DecimalField(max_digits=20, decimal_places=2)
    PurchaseOrderDate = models.DateField()
    Status = models.CharField(max_length=250, blank=True)
    ExpectedDeliveryDate = models.DateField(blank=True, null=True)
    Seller = models.ForeignKey(Seller, on_delete=models.CASCADE)
    seller_message = models.TextField(blank=True)
    
    def __str__(self):
        return f"Purchase Order {self.id}"

class PurchaseOrderItem(models.Model):
    Quantity = models.IntegerField()
    Product = models.ForeignKey(Product, on_delete=models.CASCADE)
    PurchaseOrder = models.ForeignKey(PurchaseOrder, on_delete=models.CASCADE)
    PurchaseUnitPrice = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True)
    TotalAmount = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True)

    def save(self, *args, **kwargs):
        # Calculate total amount before saving
        if self.Quantity is not None and self.PurchaseUnitPrice is not None:
            self.TotalAmount = Decimal(self.Quantity) * Decimal(self.PurchaseUnitPrice)
        super().save(*args, **kwargs)

    def __str__(self):
        return f"Purchase Order Item {self.id}"

templates/admin_login.html
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Admin Login</title>
    <style>

        body {
            font-family: Arial, sans-serif;
            background-color: #f0f0f0;
        }

        .container {
            width: 325px;
            margin: 0 auto;
            margin-top: 100px;
            background: #fff;
            padding: 20px;
            border-radius: 5px;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.2);
        }

        form {
            width: 300px;
            margin: auto;
        }

        h2 {
            text-align: center;
            margin-bottom: 20px;
        }

        label {
            font-weight: bold;
        }

        input[type="text"], input[type="password"] {
            width: 100%;
            padding: 10px;
            margin: 5px 0;
            border: 1px solid #ccc;
            border-radius: 3px;
        }

        input[type="submit"] {
            width: 100%;
            padding: 10px;
            background-color: #00b33c;
            color: #fff;
            border: none;
            border-radius: 3px;
            cursor: pointer;
        }

        input[type="submit"]:hover {
            background-color: #00b33c;
        }

        p {
            text-align: center;
            margin-top: 10px;
        }

        .error {
            color: red;
            text-align: center;
        }
    </style>
</head>
<body>
    <div class="container">
        <h2>Admin Login</h2>
        <form method="post" action="{% url 'admin_login' %}">
            {% csrf_token %}
            <label for="username">Admin name:</label>
            <input type="text" id="username" name="username" required>

            <label for="password">Password:</label>
            <input type="password" id="password" name="password" required>

            <input type="submit" value="Login">
            {% if error_message %}
            <p class="error">{{ error_message }}</p>
            {% endif %}
        
            {% if user.is_authenticated and user.is_staff %}
            <p>Welcome, Admin!</p>
            {% endif %}
        </form>
    </div>
</body>
</html>

templates/change_password.html
{% extends "theme.html" %}

{% block content %}
<style>
    .main-menu a {
    color: black !important;
}

.container {
    padding: 30px;
    margin-top: 150px;
    background-color: #fff1f0;
}
.btn {
    background-color:green;
}

</style>
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-lg-6">
                <div class="card mt-5">
                    <div class="card-body">
                        <h2 class="card-title">Change Password</h2>
                        {% if messages %}
                            {% for message in messages %}
                                <div>{{ message }}</div>
                            {% endfor %}
                        {% endif %}
                        <form method="post" class="mt-3">
                            {% csrf_token %}
                            <div class="form-group">
                                <label for="old_password">Old Password:</label>
                                <input type="password" id="old_password" name="old_password" required class="form-control">
                            </div>
                            <div class="form-group">
                                <label for="new_password">New Password:</label>
                                <input type="password" id="new_password" name="new_password" required class="form-control">
                            </div>
                            <div class="form-group">
                                <label for="confirm_password">Confirm Password:</label>
                                <input type="password" id="confirm_password" name="confirm_password" required class="form-control">
                            </div>
                            <button type="submit" class="btn btn-primary">Change Password</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/checkout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Checkout</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            background-color: #f7f7f7;
            margin: 0;
            padding: 0;
            box-sizing: border-box;
        }

        .container {
            max-width: 800px;
            margin: 20px auto;
            background-color: #f9f9f9;
            padding: 30px;
            border-radius: 15px;
            box-shadow: 0 0 20px rgba(0, 0, 0, 0.1);
        }

        h2 {
            text-align: center;
            color: #333;
            margin-bottom: 20px;
        }

        table {
            width: 100%;
            border-collapse: collapse;
            margin-bottom: 30px;
        }

        th, td {
            border: 1px solid #ddd;
            padding: 15px;
            text-align: left;
        }

        th {
            background-color: #f2f2f2;
            color: #555;
        }

        img {
            max-width: 80px;
            max-height: 80px;
            vertical-align: middle;
        }

        .address-checkbox {
            display: none;
        }

        .address-label {
            position: relative;
            cursor: pointer;
            padding-left: 25px;
            margin-right: 15px;
            line-height: 30px;
            display: block;
            color: #444;
            transition: color 0.3s ease;
        }

        .address-label:before {
            content: "";
            position: absolute;
            left: 0;
            top: 50%;
            transform: translateY(-50%);
            width: 20px;
            height: 20px;
            border: 2px solid #555;
            border-radius: 50%;
            background-color: #fff;
            transition: background-color 0.3s ease;
        }

        .address-checkbox:checked + .address-label:before {
            background-color: #21f364;
            border-color: #2196F3;
        }

        .address-checkbox:checked + .address-label:after {
            content: "\2713";
            font-size: 18px;
            position: absolute;
            top: 50%;
            left: 50%;
            transform: translate(-50%, -50%);
            color: #fff;
        }

        button {
            background-color: #2196F3;
            color: #fff;
            padding: 15px 30px;
            border: none;
            border-radius: 5px;
            cursor: pointer;
            font-size: 18px;
            transition: background-color 0.3s ease;
            display: block;
            margin: 0 auto;
        }

        button:hover {
            background-color: #0b7dda;
        }
    </style>
</head>
<body>
    <div class="popup-message" id="popupMessage">
        {% if messages %}
            {% for message in messages %}
                <p>{{ message }}</p>
            {% endfor %}
        {% endif %}
    </div>

<div class="container">

    <h2>Checkout</h2>

    <div>
        <h3>Cart Items</h3>
        <table>
            <thead>
                <tr>
                    <th>Product</th>
                    <th>Quantity</th>
                    <th>Price</th>
                </tr>
            </thead>
            <tbody>
                {% for item in cart_items %}
                <tr>
                    <td>
                        <img src="{{ item.product.product_image.url }}" alt="{{ item.product.title }}">
                        {{ item.product.name}}
                    </td>
                    <td>{{ item.quantity }}</td>
                    <td>₹{{ item.product.price }}</td>
                </tr>
                {% endfor %}
            </tbody>
            <tfoot>
                <tr>
                    <td colspan="2" align="right">Total:</td>
                    <td>₹{{ total_price }}</td>
                </tr>
            </tfoot>
        </table>
        <a href="{% url 'address_create' %}">
            <button class="add-address-button">Add Address</button>
        </a>
    </div>

    <div>
        <h3>Select Address</h3>
        <form action="{% url 'checkout' %}" method="POST">
            {% csrf_token %}
            {% for address in addresses %}
            <input type="checkbox" id="address{{ address.id }}" class="address-checkbox" name="address_id" value="{{ address.id }}">
            <label for="address{{ address.id }}" class="address-label">{{ address.address_line1 }}, {{ address.city }}, {{ address.country }}</label>
            {% endfor %}
            <button type="submit">Proceed to Payment</button>
            <a href="{% url 'index' %}">
                <a href="/" class="btn">Go to Home</a> <!-- "Go to Home" button -->
              </a>
            
        </form>
    </div>


</div>
<!-- checkout-area end -->
<script>
    function selectAddress(addressId) {
      const addressIdInput = document.getElementById('address-id');
      addressIdInput.value = addressId;
    }
    
    </script>

</body>
</html>

templates/customer_dashboard.html
{% extends 'theme.html' %}

{% block content %}
{% load static %}
  <style>
    body {
      font-family: 'Arial', sans-serif;
      margin: 0;
      padding: 0;
      background-color: #f8f9fa;
    }

    .dashboard {
      display: flex;
      justify-content: center;
      align-items: center;
      flex-wrap: wrap;
      gap: 20px;
      padding: 20px;
    }

    .card {
      width: 200px;
      height: 150px;
      border-radius: 10px;
      display: flex;
      flex-direction: column;
      justify-content: center;
      align-items: center;
      text-align: center;
      text-decoration: none;
      color: #333;
      background-color: #fff;
      box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);
      transition: transform 0.3s ease;
    }

    .card:hover {
      transform: translateY(-5px);
      box-shadow: 0 6px 12px rgba(0, 0, 0, 0.1);
    }

    .icon {
      font-size: 40px;
      margin-bottom: 10px;
      color: #333;
    }

    .card h3 {
      margin: 0;
      color: #333;
    }

    .main-menu a {
      color: black !important;
    }
  </style>
</head>
<body>
  <div class="dashboard">
    <div class="card">
      <a href="{% url 'order_list' %}">
        <i class="fas fa-shopping-basket icon"></i>
        <h3>My Orders</h3>
      </a>
    </div>
    <div class="card">
      <a href="{% url 'edit_customer' %}">
        <i class="fas fa-user-circle icon"></i>
        <h3>My Profile</h3>
      </a>
    </div>
    <div class="card">
      <a href="{% url 'address_list' %}">
        <i class="fas fa-map-marker-alt icon"></i>
        <h3>My Addresses</h3>
      </a>
    </div>
  </div>
{% endblock %}

templates/edit_customer.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Edit Customer Profile</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            background-color: #f5f5f5;
            margin: 0;
            padding: 0;
        }

        .container {
            max-width: 400px;
            margin: 20px auto;
            padding: 20px;
            background-color: #f9f9f9;
            border-radius: 8px;
            box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1);
        }

        h2 {
            text-align: center;
            color: #333;
            margin-bottom: 20px;
        }

        form {
            display: flex;
            flex-direction: column;
        }

        label {
            margin-bottom: 8px;
            color: #555;
            font-weight: bold;
        }

        input[type="text"],
        input[type="email"],
        input[type="tel"] {
            padding: 10px;
            margin-bottom: 20px;
            border: 1px solid #ccc;
            border-radius: 4px;
            width: 100%;
            box-sizing: border-box;
            transition: border-color 0.3s ease;
        }

        input[type="text"]:focus,
        input[type="email"]:focus,
        input[type="tel"]:focus {
            border-color: #007bff;
        }

        button[type="submit"],
        button[type="button"] {
            padding: 12px;
            background-color: #007bff;
            color: #fff;
            border: none;
            border-radius: 4px;
            cursor: pointer;
            transition: background-color 0.3s ease;
            width: 100%;
            max-width: 200px;
            font-size: 16px;
        }

        button[type="submit"]:hover,
        button[type="button"]:hover {
            background-color: #0a365b;
        }

        /* Increase space between buttons */
        button[type="submit"] {
            margin-bottom: 10px;
        }

        /* Style the "Change Password" button */
        button[type="button"] {
            background-color:green;
        }

        button[type="button"]:hover {
            background-color:#1ed415;
        }
    </style>
</head>
<body>
    <div class="container">
        <h2> My Profile</h2>
        <form method="post">
            {% csrf_token %}
            <label for="full-name">Full Name:</label>
            <input type="text" id="full-name" name="full-name" value="{{ customer.customer_name }}" required>
            <label for="your-email">Email:</label>
            <input type="email" id="your-email" name="your-email" value="{{ customer.email }}" required>
            <label for="phone-number">Phone Number:</label>
            <input type="tel" id="phone-number" name="phone-number" value="{{ customer.contact_number }}" required>
            <button type="submit">Update Profile</button>
        </form>
        <button type="button" onclick="location.href='{% url 'change_password' %}'">Change Password</button>
    </div>
</body>
</html>

templates/index.html
{% extends 'theme.html' %}

{% load static %}
<head>
  <link rel="stylesheet" href="https://unpkg.com/swiper/swiper-bundle.min.css" />
  <script src="https://unpkg.com/swiper/swiper-bundle.min.js"></script>
</head>

{% block title %}Home{% endblock title %}



{% block content %}
  <style>
    .product-card {
      width: 80%;
      margin-bottom: 20px;
      height: 400px; /* Set the desired height for the cards */
    }

    .product-image {
      width: 100%;
      height: 250px; /* Set the desired height */
      object-fit: cover;
    }

    .product-buttons {
      position: absolute;
      bottom: 0;
      left: 50%;
      transform: translateX(-50%);
    }

    .btn-primary {
      background-color: #0e9220; /* Primary color for buttons */
      border: none;
      transition: background-color 0.3s ease;
    }

    .btn-primary:hover {
      background-color: #0056b3; /* Darker shade on hover */
    }

    .shop-title {
      margin: 0;
      padding: 10px;
      cursor: pointer;
      background-color: #074e0d;
    }

    .shop-link {
      padding: 0;
      margin: 0;
      display: none; /* Hide initially */
    }

    .shop-link li {
      list-style-type: none;
      margin: 0;
      padding: 0;
    }

    .shop-link li a {
      text-decoration: none;
      color: #333;
      display: block;
      padding: 10px;
    }

    .col-md-3 {
      flex: 0 0 calc(33.33% - 20px); /* Adjusted width with space */
      max-width: calc(33.33% - 20px); /* Adjusted max-width with space */
      padding: 0 10px; /* Added padding for space between products */

    }

    .swiper-container {
    width: 100%;
    height: 600px; /* Adjust the height as needed */
    margin-bottom: 20px;
  }
  .swiper-slide img {
    width: 100%;
    height: 100%;
    object-fit: cover;
  }
  .shop-title {
      color: white; /* Change category text color to white */
    }
  </style>
  <div class="swiper-container">
    <div class="swiper-wrapper">
        <div class="swiper-slide"><img src="{% static 'banner 2.png' %}" alt="Banner 1"></div>
        
        
        <!-- <div class="swiper-slide"><img src="{% static 'images/banner3.jpg' %}" alt="Banner 3"></div> -->
        <!-- Add more slides as needed -->
    </div>

  <div class="shop-widget">
    <h3 class="shop-title">Categories</h3>
  
    <ul class="shop-link">
      {% for category in categories %}
        <li>
          <a href="{% url 'category_products' category.id %}">
            <h6>{{ category.category_name }}</h6>
          </a>
          <ul>
            {% for subcategory in category.subcategory_set.all %}
              <li>
                <a href="{% url 'subcategory_products' subcategory.id %}">
                  {{ subcategory.subcategory_name }}
                </a>
              </li>
            {% endfor %}
          </ul>
        </li>
      {% endfor %}
    </ul>
  </div>
  

  <div class="container mt-40 mb-40">
    <div class="row">
      {% for product in products %}
        <div class="col-md-3 mt-3">
          <div class="card product-card position-relative">
            <img src="{{ product.image.url }}" class="card-img img-fluid product-image" alt="{{ product.name }}">
            <span class="wishlist-icon position-absolute top-0 start-0"> 
              
              <a href="{% url 'add_to_wishlist' product.id %}" class="btn btn-primary">
                <i class="fas fa-heart"></i>
            </a>
            </span>
            {% if product.quantity_in_stock == 0 %}
                                            <span class="stock-status" style="font-size: larger; color: brown;">Out of Stock</span>
                                        {% elif product.quantity_in_stock < product.reorder_level %}
                                            <span class="stock-status" style="font-size: larger; color: brown;">Limited Stock</span>
                                        {% endif %}
            <div class="card-body bg-light text-center">
              <h5 class="card-title"><a href="{% url 'product_details' product.id %}">{{ product.name }}</a></h5>
              <p class="card-text">₹{{ product.price }}</p>
              {% if product.quantity_in_stock > 0 %}
            </div>
            <div class="product-buttons">
              <form id="add-to-cart-form" action="{% url 'add_to_cart' %}" method="post">
                {% csrf_token %}
                <input type="hidden" name="product_id" value="{{ product.id }}">
                <input type="hidden" name="quantity" value="1">
                <button type="submit" id="cart-button" class="btn btn-primary btn-add-to-cart">Add to Cart</button>
                {% endif %}
              </form>
            </div>
          </div>
        </div>
      {% endfor %}
    </div>
  </div>

  <script>
    // JavaScript for collapsible div
    document.addEventListener("DOMContentLoaded", function() {
      var shopTitle = document.querySelector('.shop-title');
      var shopLink = document.querySelector('.shop-link');
      
      shopTitle.addEventListener('click', function() {
        if (shopLink.style.display === 'none') {
          shopLink.style.display = 'block';
        } else {
          shopLink.style.display = 'none';
        }
      });
    });

    var swiper = new Swiper('.swiper-container', {
        loop: true,
        pagination: {
            el: '.swiper-pagination',
            clickable: true,
        },
        navigation: {
            nextEl: '.swiper-button-next',
            prevEl: '.swiper-button-prev',
        },
        autoplay: {
            delay: 5000,
        },
    });
  </script>

{% endblock %}

templates/order_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
  </head>
  <body>
    <h1>Order List</h1>
    <ul>
      {% for order in orders %}
      <li>
        <a href="{% url 'order_detail' order.id %}">
          Order ID: {{ order.id }} - Status: {{ order.status }}
        </a>
      </li>
      {% empty %}
      <li>No orders found.</li>
      {% endfor %}
    </ul>
  </body>
  </html>

templates/reset_password_email.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Password Reset Email</title>
</head>
<body>
    <p>Hello {{ user.username }},</p>
    <p>You requested to reset your password. Click the link below to reset your password:</p>
    <a href="{{ reset_password_url }}">Reset Password</a>
</body>
</html>